import Head from "next/head";
import Header from "./components/Header";
import Hero from "./Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mohit Maroliya Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <div className="min-h-full">
        <Header />
        <Hero />
      </div>
    </>
  );
}
